#!/bin/sh

# backup home to usb
rsync -aAXvzP --ignore-errors --delete --progress \
--exclude downloads \
--exclude music \
--exclude video \
--exclude torrents \
--exclude .nv \
--exclude .var \
--exclude .cache \
--exclude .cargo \
--exclude .dbus \
--exclude .mozilla \
--exclude .sndio \
--exclude .config/chromium \
--exclude .config/eduke32 \
/home/djwilcox /mnt/usb
