#!/bin/sh

# backup home to usb
rsync -aAXvzP --ignore-errors --delete --progress \
--exclude downloads \
--exclude music \
--exclude videos \
--exclude torrents \
--exclude .nv \
--exclude .var \
--exclude .cache \
--exclude .cargo \
--exclude .dbus \
--exclude .mozilla \
--exclude .sndio \
/home/djwilcox /mnt/usb/djwilcox/backup
