#!/bin/sh

# connect to emacs socket
#/usr/local/bin/emacsclient -s /tmp/emacs1001/server -c -F "((name . \"emacs-capture\") (height . 25) (width . 100))" "$@"
#/usr/local/bin/emacsclient -c -F "((name . \"emacs-capture\") (height . 25) (width . 100))" "$@"

# open capture links in emacs
/usr/local/bin/emacsclient "$@"
