#!/bin/sh

# transmission add magnet link from browser

# if script is run without arguments exit
[ $# -gt 0 ] || exit


# check if network namespace exists on nixos
if [ -d /var/run/netns/vpn ]; then
    doas namespace transmission-remote --add "$@"
else
    transmission-remote --add "$@"
fi
