#!/usr/bin/env bash

# enable ipv4 forwarding
sysctl net.inet.ip.forwarding=1

# routes
ifconfig "$dev" "$ifconfig_local" "$ifconfig_remote" fib 1
route add -net "$ifconfig_remote" -iface "$dev" -fib 1
route add default "$ifconfig_remote" -fib 1

# openvpn-up
LANIF="${OPENVPN_lanif}"
ANCHOR="${OPENVPN_anchor}"

/sbin/pfctl -a "${ANCHOR}" -F rules
/sbin/pfctl -a "${ANCHOR}" -F nat
/sbin/pfctl -a "${ANCHOR}" -f - <<EOT
pass in on $LANIF reply-to ($dev $ifconfig_remote) to $ifconfig_local
pass out on $LANIF route-to ($dev $ifconfig_remote) from $ifconfig_local
antispoof quick for "$dev"
EOT
