#!/usr/bin/env bash

# openvpn-down
#=============

route delete -net 192.168.1.0/24 -iface "$dev" -fib 1
route delete default -fib 1

ANCHOR="${OPENVPN_anchor}"

/sbin/pfctl -a "${ANCHOR}" -F rules
/sbin/pfctl -a "${ANCHOR}" -F nat
