#!/usr/bin/env bash

# disable ipv4 forwarding
sysctl net.inet.ip.forwarding=0

# openvpn-down
#=============

# route
#route delete default -fib 1

ANCHOR="${OPENVPN_anchor}"

/sbin/pfctl -a "${ANCHOR}" -F rules
/sbin/pfctl -a "${ANCHOR}" -F nat
