#!/usr/bin/env bash

# routes
route add -net 192.168.1.0/24 -iface "$dev" -fib 1
route add default 192.168.1.1 -fib 1

# openvpn-up
LANIF="${OPENVPN_lanif}"
ANCHOR="${OPENVPN_anchor}"

/sbin/pfctl -a "${ANCHOR}" -F rules
/sbin/pfctl -a "${ANCHOR}" -F nat
/sbin/pfctl -a "${ANCHOR}" -f - <<EOT
pass out quick on "$dev" inet keep state
antispoof quick for "$dev"
EOT
