#!/usr/local/bin/bash

# geli container mount and umount script
#=======================================

# check to see if script was run as root
if [[ $UID -ne 0 ]]; then
  echo "$0 must be run as root using sudo, make your own sandwich"
  exit 1
fi

# Create the prompt
PS3="Enter your choice: "
options=("mount" "umount" "quit")
OLD_IFS=${IFS}; #ifs space seperator
IFS=$'\t\n' #change ifs seperator from spaces to new line

# container
container="/usr/home/djwilcox/documents/disk.img"
# geli key
gelikey="/usr/home/djwilcox/.ossuary/ossuary.key"

# mdconfig device - remove white space from end of command with sed
loopdevice=$(mdconfig -lf "$container" | sed 's/[ \t]*$//')
# geli device
loopcrypt="/dev/${loopdevice}.eli"

# select and case statement
select opt in "${options[@]}"; do
case $opt in
  mount)
        { loop=$(mdconfig -a -t vnode -f "$container") && \
        geli attach -k "$gelikey" "$loop" && \
        poolname=$(zdb -l /dev/md0.eli | awk -F\' '/[[:blank:]]name/ {print $2; exit;}') && \
        zpool import "$poolname"; } || { mdconfig -du "$loopdevice" && break; }
        break;;
  umount)
        { poolname=$(zdb -l /dev/md0.eli | awk -F\' '/[[:blank:]]name/ {print $2; exit;}') && \
        zfs umount "$poolname" && \
        zpool export "$poolname" && \
        sleep 1 && \
        geli detach "$loopcrypt" && \
        mdconfig -du "$loopdevice"; } || { printf "%s\n" 'container not mounted' && break; }
	break;;
  quit) 
	echo "Quitting"
	IFS=${OLD_IFS}
	break;;
  *)    echo "Usage: ossuary [ mount | umount | quit ]";;
esac
done
