#!/usr/bin/env bash

# luks container mount and umount script
#=======================================

# check to see if script was run as root
if [[ $UID -ne 0 ]]; then
  echo "$0 must be run as root using sudo, make your own sandwich"
  exit 1
fi

# Create the prompt
PS3="Enter your choice: "
options=("mount" "umount" "quit")
OLD_IFS=${IFS}; #ifs space seperator
IFS=$'\t\n' #change ifs seperator from spaces to new line

# container variables
loop="/dev/md0"
loopcrypt="/dev/md0.eli"
container="/usr/home/djwilcox/documents/disk.img"
gelikey="/usr/home/djwilcox/.ossuary/ossuary.key"
poolname="crypt"

# select and case statement
select opt in "${options[@]}"; do
case $opt in
  mount)
        mdconfig -a -t vnode -f "$container" -u 0
        geli attach -k "$gelikey" "$loop"
        zpool import "$poolname"
        break;;
  umount)
        zfs umount "$poolname"
        zpool export "$poolname"
		  sleep 1
        geli detach "$loopcrypt"
        mdconfig -d -u 0
	break;;
  quit) 
	echo "Quitting"
	IFS=${OLD_IFS}
	break;;
  *)    echo "Usage: ossuary [ mount | umount | quit ]";;
esac
done
