#!/bin/sh

# synergy-core server
usage="usage: $(basename "$0") [ start | stop ]"

# check if 1 argument is passed to the script
[ $# = 1 ] || { printf "%s\n" "$usage"; exit 1; }

# case statement
input="$1"
case "$input" in
  start)
        # if server isnt running start it
        synergy-core --server --address 192.168.1.3:24800 --config /usr/local/etc/synergy.conf
        break;;
  stop)
        # if server is running stop it
        pkill synergy-core
        break;;
  *)    printf "%s\n" "$usage";;
esac
