#!/bin/sh

#===============================================================================
# openvpn split route with setfibs
#===============================================================================


#===============================================================================
# openvpn up script
#===============================================================================

up() {
# routes
mask="$(ifconfig -f inet:cidr ${dev} | awk '/inet/ {print $2}')"
ifconfig "${dev}" inet "${mask}" "${ifconfig_local}" "${ifconfig_local}" fib 1
route add -net default "${ifconfig_local}" -fib 1

# openvpn-up
LANIF="${OPENVPN_lanif}"
ANCHOR="${OPENVPN_anchor}"

# pf rules
/sbin/pfctl -a "${ANCHOR}" -F rules
/sbin/pfctl -a "${ANCHOR}" -F nat
/sbin/pfctl -a "${ANCHOR}" -f - <<EOT
pass out quick on "${dev}" inet modulate state
antispoof quick for "${dev}"
EOT
}


#===============================================================================
# openvpn down script
#===============================================================================

down() {
ANCHOR="${OPENVPN_anchor}"

/sbin/pfctl -a "${ANCHOR}" -F rules
/sbin/pfctl -a "${ANCHOR}" -F nat
}

"$script_type" "$@"
