#!/bin/sh

#input=$(wlrctl toplevel list | awk -F: '{print $1}' | tofi)
#wlrctl toplevel activate app_id:"${input}"

input=$(wlrctl toplevel list | awk -F': ' '{print $2}' | tofi)
wlrctl toplevel activate title:"${input}"
